import Link from "next/link";
import { notFound } from "next/navigation";
import { getAuditPage } from "@/lib/audit-pages";
import { AnalyzePageButton } from "./AnalyzePageButton";
import { Collapsible, CopyButton, PreviewFrame } from "./ClientBits";

function VerdictList({ title, items, tone }: { title: string; items: string[]; tone: "good" | "bad" | "neutral" }) {
	const color =
		tone === "good" ? "var(--color-success)" : tone === "bad" ? "var(--color-danger)" : "var(--color-accent)";
	return (
		<div className="card p-5">
			<h3 className="font-semibold" style={{ color }}>
				{title}
			</h3>
			{items.length === 0 ? (
				<p className="mt-2 text-sm text-[var(--color-muted)]">None detected.</p>
			) : (
				<ul className="mt-2 space-y-1.5">
					{items.map((it, i) => (
						<li key={i} className="text-sm text-[var(--color-muted)] flex gap-2">
							<span style={{ color }}>•</span>
							<span>{it}</span>
						</li>
					))}
				</ul>
			)}
		</div>
	);
}

export default async function AuditPageDetail({ params }: { params: Promise<{ id: string }> }) {
	const { id } = await params;
	const detail = await getAuditPage(id);
	if (!detail) notFound();

	const { record, ai, aiStatus, aiError } = detail;
	const kb = (record.htmlBytes / 1024).toFixed(0);

	return (
		<div className="space-y-6">
			<div>
				<Link href="/audit" className="text-sm text-[var(--color-muted)] hover:text-[var(--color-fg)]">
					← Back to audit
				</Link>
			</div>

			<div className="flex flex-wrap items-start justify-between gap-4">
				<div className="min-w-0">
					<h1 className="text-2xl font-bold break-words">{record.title || "Untitled page"}</h1>
					<a
						href={record.url}
						target="_blank"
						rel="noopener noreferrer"
						className="mt-1 inline-block break-all font-mono text-sm text-[var(--color-accent)] hover:underline"
					>
						{record.url} ↗
					</a>
					<div className="mt-2 flex flex-wrap gap-2 text-[10px] uppercase tracking-wide text-[var(--color-muted)]">
						<span className="rounded border border-[var(--color-border)] px-2 py-0.5">HTTP {record.status}</span>
						<span className="rounded border border-[var(--color-border)] px-2 py-0.5">
							{record.wordCount} words
						</span>
						<span className="rounded border border-[var(--color-success)]/40 px-2 py-0.5 text-[var(--color-success)]">
							HTML stored · {kb} KB
						</span>
						{record.signals.schemaTypes.length > 0 && (
							<span className="rounded border border-[var(--color-border)] px-2 py-0.5">
								schema: {record.signals.schemaTypes.join(", ")}
							</span>
						)}
					</div>
				</div>
				<AnalyzePageButton pageId={id} hasResult={!!ai} />
			</div>

			{aiStatus === "error" && aiError && (
				<div className="card p-4 border-[var(--color-danger)]/40 text-sm text-[var(--color-danger)]">
					Last AI run failed: {aiError}
				</div>
			)}

			{/* Deterministic rule verdicts */}
			<div className="grid gap-4 lg:grid-cols-2">
				<VerdictList title="What's working" items={record.working} tone="good" />
				<VerdictList title="What's not working" items={record.notWorking} tone="bad" />
			</div>
			{record.ruleIssues.length > 0 && <VerdictList title="Rule issues" items={record.ruleIssues} tone="neutral" />}

			{/* AI agent output */}
			<div className="space-y-4">
				<h2 className="text-lg font-bold">AI auditor {ai ? `· ${ai.model}` : ""}</h2>

				{!ai && aiStatus !== "running" && (
					<div className="card p-6 text-sm text-[var(--color-muted)]">
						No AI analysis yet. Click <strong>Run AI analysis</strong> to get gaps, opportunities, suggested
						fixes, and a corrected version of this page generated by your connected model.
					</div>
				)}
				{aiStatus === "running" && !ai && (
					<div className="card p-6 text-sm text-[var(--color-muted)]">AI agent is running on this page…</div>
				)}

				{ai && (
					<>
						<div className="grid gap-4 lg:grid-cols-2">
							<VerdictList title="AI · working well" items={ai.working} tone="good" />
							<VerdictList title="AI · not working" items={ai.notWorking} tone="bad" />
						</div>
						<VerdictList title="Gaps & opportunities" items={ai.gaps} tone="neutral" />

						{ai.suggestedFixes.length > 0 && (
							<div className="card p-5">
								<h3 className="font-semibold">Suggested fixes</h3>
								<div className="mt-3 space-y-3">
									{ai.suggestedFixes.map((f, i) => (
										<div
											key={i}
											className="rounded-md border border-[var(--color-border)] bg-[var(--color-bg)] p-3"
										>
											<div className="text-sm font-medium">{f.issue}</div>
											<div className="mt-1 text-sm text-[var(--color-muted)]">
												<span className="text-[var(--color-success)]">Fix: </span>
												{f.fix}
											</div>
										</div>
									))}
								</div>
							</div>
						)}

						{ai.correctedHtml && (
							<div className="card p-5">
								<div className="flex items-center justify-between">
									<h3 className="font-semibold">Corrected version (HTML)</h3>
									<CopyButton text={ai.correctedHtml} label="Copy HTML" />
								</div>
								<p className="mt-1 text-xs text-[var(--color-muted)]">
									Your original HTML with targeted patches applied — content is preserved, never rewritten
									wholesale. Placeholders like [DESCRIBE: …] need your real data.
								</p>
								{(ai.appliedPatches?.length ?? 0) > 0 && (
									<ul className="mt-2 flex flex-wrap gap-1.5">
										{(ai.appliedPatches ?? []).map((p, i) => (
											<li
												key={i}
												className="rounded border border-[var(--color-success)]/40 px-2 py-0.5 text-[10px] uppercase tracking-wide text-[var(--color-success)]"
											>
												{p}
											</li>
										))}
									</ul>
								)}
								<PreviewFrame html={ai.correctedHtml} />
								<pre className="mt-3 max-h-[420px] overflow-auto rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)] p-3 text-xs text-[var(--color-muted)]">
									{ai.correctedHtml}
								</pre>
							</div>
						)}
					</>
				)}
			</div>

			{/* Stored source */}
			<Collapsible title="Stored HTML" subtitle={`${kb} KB parsed & saved`}>
				<pre className="max-h-[420px] overflow-auto p-4 text-xs text-[var(--color-muted)]">{record.html}</pre>
			</Collapsible>
			<Collapsible title="Extracted readable text" subtitle={`${record.wordCount} words`}>
				<pre className="max-h-[360px] overflow-auto whitespace-pre-wrap p-4 text-xs text-[var(--color-muted)]">
					{record.text}
				</pre>
			</Collapsible>
		</div>
	);
}
